services:
  proxy:
    image: envoyproxy/envoy-dev:latest
    command: ["--component-log-level", "wasm:debug", "-c", "/etc/envoy.yaml"]
    volumes:
      - ./envoy.yaml:/etc/envoy.yaml
      - ./target/wasm32-unknown-unknown/release/geoip_filter.wasm:/etc/geoip_filter.wasm
      - ./target/wasm32-unknown-unknown/release/singleton_service.wasm:/etc/singleton_service.wasm
    ports:
      - 10000:10000 # httpbin listener
      - 9901:9901 # admin server
  httpbin:
    image: kennethreitz/httpbin:latest
  mmdb:
    image: halverneus/static-file-server:latest
    volumes:
      - ./GeoLite2-Country.mmdb:/web/GeoLite2-Country.mmdb
    ports:
      - 8080:8080 # http server
